version: 2.1
workflows:
  version: 2
  just_push:
      jobs:
      - pantheon/push
      - playground/backstop:
          requires:
             - pantheon/push
orbs:
  pantheon: pantheon-systems/pantheon@0.1.0
  playground: fauxalgore/playground@0.0.2

